package com.sdcxv.ams.model;

import java.util.Date;

public class Attendance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.attendance_id
     *
     * @mbggenerated
     */
    private Integer attendanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.student_id
     *
     * @mbggenerated
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.teacher_id
     *
     * @mbggenerated
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.attendance_time
     *
     * @mbggenerated
     */
    private Date attendanceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.attendance_id
     *
     * @return the value of attendance.attendance_id
     * @mbggenerated
     */
    public Integer getAttendanceId() {
        return attendanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.attendance_id
     *
     * @param attendanceId the value for attendance.attendance_id
     * @mbggenerated
     */
    public void setAttendanceId(Integer attendanceId) {
        this.attendanceId = attendanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.student_id
     *
     * @return the value of attendance.student_id
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.student_id
     *
     * @param studentId the value for attendance.student_id
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.teacher_id
     *
     * @return the value of attendance.teacher_id
     * @mbggenerated
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.teacher_id
     *
     * @param teacherId the value for attendance.teacher_id
     * @mbggenerated
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.course_id
     *
     * @return the value of attendance.course_id
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.course_id
     *
     * @param courseId the value for attendance.course_id
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.attendance_time
     *
     * @return the value of attendance.attendance_time
     * @mbggenerated
     */
    public Date getAttendanceTime() {
        return attendanceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.attendance_time
     *
     * @param attendanceTime the value for attendance.attendance_time
     * @mbggenerated
     */
    public void setAttendanceTime(Date attendanceTime) {
        this.attendanceTime = attendanceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.status
     *
     * @return the value of attendance.status
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.status
     *
     * @param status the value for attendance.status
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.create_time
     *
     * @return the value of attendance.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.create_time
     *
     * @param createTime the value for attendance.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}