package com.sdcxv.ams.model;

import java.util.Date;

public class CourseTime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_time.course_time_id
     *
     * @mbggenerated
     */
    private Integer courseTimeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_time.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_time.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_time.course_time
     *
     * @mbggenerated
     */
    private Date courseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_time.course_time_id
     *
     * @return the value of course_time.course_time_id
     *
     * @mbggenerated
     */
    public Integer getCourseTimeId() {
        return courseTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_time.course_time_id
     *
     * @param courseTimeId the value for course_time.course_time_id
     *
     * @mbggenerated
     */
    public void setCourseTimeId(Integer courseTimeId) {
        this.courseTimeId = courseTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_time.name
     *
     * @return the value of course_time.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_time.name
     *
     * @param name the value for course_time.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_time.course_id
     *
     * @return the value of course_time.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_time.course_id
     *
     * @param courseId the value for course_time.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_time.course_time
     *
     * @return the value of course_time.course_time
     *
     * @mbggenerated
     */
    public Date getCourseTime() {
        return courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_time.course_time
     *
     * @param courseTime the value for course_time.course_time
     *
     * @mbggenerated
     */
    public void setCourseTime(Date courseTime) {
        this.courseTime = courseTime;
    }
}