package com.sdcxv.ams.model;

import java.util.Date;

public class CourseList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_list.course_list_id
     *
     * @mbggenerated
     */
    private Integer courseListId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_list.student_id
     *
     * @mbggenerated
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_list.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_list.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_list.course_list_id
     *
     * @return the value of course_list.course_list_id
     *
     * @mbggenerated
     */
    public Integer getCourseListId() {
        return courseListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_list.course_list_id
     *
     * @param courseListId the value for course_list.course_list_id
     *
     * @mbggenerated
     */
    public void setCourseListId(Integer courseListId) {
        this.courseListId = courseListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_list.student_id
     *
     * @return the value of course_list.student_id
     *
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_list.student_id
     *
     * @param studentId the value for course_list.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_list.course_id
     *
     * @return the value of course_list.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_list.course_id
     *
     * @param courseId the value for course_list.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_list.update_time
     *
     * @return the value of course_list.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_list.update_time
     *
     * @param updateTime the value for course_list.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}