package com.sdcxv.ams.mapper;

import com.sdcxv.ams.model.Attendance;

public interface AttendanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer attendanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated
     */
    int insert(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated
     */
    int insertSelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated
     */
    Attendance selectByPrimaryKey(Integer attendanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Attendance record);
}