package com.sdcxv.ams.mapper;

import com.sdcxv.ams.model.CourseList;

public interface CourseListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer courseListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated
     */
    int insert(CourseList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated
     */
    int insertSelective(CourseList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated
     */
    CourseList selectByPrimaryKey(Integer courseListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CourseList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CourseList record);
}