package com.sdcxv.ams.mapper;

import com.sdcxv.ams.model.CourseTime;

public interface CourseTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_time
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer courseTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_time
     *
     * @mbggenerated
     */
    int insert(CourseTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_time
     *
     * @mbggenerated
     */
    int insertSelective(CourseTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_time
     *
     * @mbggenerated
     */
    CourseTime selectByPrimaryKey(Integer courseTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_time
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CourseTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_time
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CourseTime record);
}